# https://developers.home-assistant.io/docs/add-ons/configuration
name: "Amber2Sigen"
version: "1.0.8"
slug: "amber2sigen"
description: "Sync Amber Electric prices to Sigen Energy Controller tariffs"
url: "https://github.com/starlit-rocketship/amber2sigen-addon"
documentation: "https://github.com/starlit-rocketship/amber2sigen-addon#readme"
arch:
  - amd64
  - aarch64
  - armv7
init: false
startup: "application"
image: "ghcr.io/starlit-rocketship/amber2sigen-addon-{arch}"
logo: "logo.png"
icon: "icon.png"


# If you want to persist anything, /data is available by default (no map needed)
# map:
#   - share:rw

options:
  amber_token: "psk_xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"  # get from https://amber.com.au/dashboard/api-keys
  station_id: ""
  interval: 30
  tz_override: "Australia/Melbourne"
  sigen_user: ""
  sigen_password: ""         # NEW optional placeholder (not used yet)
  sigen_device_id: ""
  sigen_pass_enc: ""
  sigen_bearer: ""
  plan_name: "Amber Live"
  align: "end"
  advanced: "predicted"
  use_current: true
  dry_run: false
  mqtt_enabled: false
  mqtt_host: "core-mosquitto"
  mqtt_port: 1883
  mqtt_username: ""
  mqtt_password: ""
  mqtt_topic_prefix: "amber2sigen"

schema:
  amber_token: "str"
  station_id: "int"
  interval: "list(5|30)"     # ← ONLY 5 or 30 now
  tz_override: "str?"
  sigen_user: "str"
  sigen_password: "password?"     # ← optional (not used unless we add login helper)
  sigen_device_id: "str?"
  sigen_pass_enc: "password?"
  sigen_bearer: "str?"
  plan_name: "str"
  align: "list(start|end)?"
  advanced: "list(low|predicted|high)"
  use_current: "bool"
  dry_run: "bool"
  mqtt_enabled: "bool"
  mqtt_host: "str?"
  mqtt_port: "int?"
  mqtt_username: "str?"
  mqtt_password: "str?"
  mqtt_topic_prefix: "str?"

# Optional watchdog - uncomment if you add a tiny HTTP health port:
# watchdog:
#   http: "http://[HOST]:[PORT:9998]/health"
