name: Build & Push Add-on Image
on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  workflow_dispatch: {}

permissions:
  contents: write         # <-- allow committing DOCS.md
  packages: write

concurrency:
  group: addon-${{ github.ref }}
  cancel-in-progress: false

jobs:
  docs:
    runs-on: ubuntu-latest
    # only commit on branch pushes (not tags)
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/heads/')
    steps:
      - uses: actions/checkout@v4
      - name: Sync README to add-on DOCS.md
        run: |
          cp README.md amber2sigen/DOCS.md
      - name: Commit DOCS.md
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "docs: sync README -> amber2sigen/DOCS.md"
          file_pattern: amber2sigen/DOCS.md

  build:
    runs-on: ubuntu-latest
    needs: [docs]          # <-- wait for docs job
    permissions: { contents: read, packages: write }
    strategy:
      matrix:
        include:
          - arch: amd64
            platform: linux/amd64
            base_image: ghcr.io/home-assistant/amd64-base:3.21
          - arch: aarch64
            platform: linux/arm64
            base_image: ghcr.io/home-assistant/aarch64-base:3.21
          - arch: armv7
            platform: linux/arm/v7
            base_image: ghcr.io/home-assistant/armv7-base:3.21
    env:
      IMAGE_NAME: ghcr.io/starlit-rocketship/amber2sigen-addon
      VERSION: 1.0.20
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: starlit-rocketship
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Build ${{ matrix.arch }} and push
        uses: docker/build-push-action@v6
        with:
          context: ./amber2sigen
          file: ./amber2sigen/Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          build-args: |
            BUILD_FROM=${{ matrix.base_image }}
          tags: |
            ${{ env.IMAGE_NAME }}-${{ matrix.arch }}:latest
            ${{ env.IMAGE_NAME }}-${{ matrix.arch }}:${{ env.VERSION }}

  manifest:
    runs-on: ubuntu-latest
    needs: [build]
    permissions: { contents: read, packages: write }
    env:
      IMAGE_NAME: ghcr.io/starlit-rocketship/amber2sigen-addon
      VERSION: 1.0.20
    steps:
      - uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: starlit-rocketship
          password: ${{ secrets.GHCR_TOKEN }}
      - name: Create multi-arch tag (latest)
        run: |
          docker buildx imagetools create \
            -t ${IMAGE_NAME}:latest \
            ${IMAGE_NAME}-amd64:latest \
            ${IMAGE_NAME}-aarch64:latest \
            ${IMAGE_NAME}-armv7:latest
      - name: Create multi-arch tag (version)
        run: |
          docker buildx imagetools create \
            -t ${IMAGE_NAME}:${VERSION} \
            ${IMAGE_NAME}-amd64:${VERSION} \
            ${IMAGE_NAME}-aarch64:${VERSION} \
            ${IMAGE_NAME}-armv7:${VERSION}
