name: Build & Push Add-on Image

on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        arch: [ amd64, aarch64, armv7 ]
    env:
      IMAGE_NAME: ghcr.io/starlit-rocketship/amber2sigen-addon
      VERSION: 1.0.0
    steps:
      - uses: actions/checkout@v4

      - name: Set up QEMU
      - uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
      - uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build ${{ matrix.arch }} and push
        uses: docker/build-push-action@v6
        with:
          context: ./amber2sigen
          platforms: linux/${{ matrix.arch }}
          push: true
          build-args: |
            BUILD_FROM=ghcr.io/home-assistant/${{ matrix.arch }}-base:2025.05.0
          tags: |
            ${{ env.IMAGE_NAME }}-${{ matrix.arch }}:latest
            ${{ env.IMAGE_NAME }}-${{ matrix.arch }}:${{ env.VERSION }}

  manifest:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      packages: write
    steps:
      - name: Create and push multi-arch manifest (latest)
        run: |
          docker manifest create ghcr.io/starlit-rocketship/amber2sigen-addon:latest \
            --amend ghcr.io/starlit-rocketship/amber2sigen-addon-amd64:latest \
            --amend ghcr.io/starlit-rocketship/amber2sigen-addon-aarch64:latest \
            --amend ghcr.io/starlit-rocketship/amber2sigen-addon-armv7:latest
          docker manifest push ghcr.io/starlit-rocketship/amber2sigen-addon:latest

      - name: Create and push multi-arch manifest (version)
        env:
          VERSION: 1.0.0
        run: |
          docker manifest create ghcr.io/starlit-rocketship/amber2sigen-addon:${VERSION} \
            --amend ghcr.io/starlit-rocketship/amber2sigen-addon-amd64:${VERSION} \
            --amend ghcr.io/starlit-rocketship/amber2sigen-addon-aarch64:${VERSION} \
            --amend ghcr.io/starlit-rocketship/amber2sigen-addon-armv7:${VERSION}
          docker manifest push ghcr.io/starlit-rocketship/amber2sigen-addon:${VERSION}
