name: Build & Push Add-on Image
on:
  push:
    branches: [ main ]
    tags: [ 'v*.*.*' ]
  workflow_dispatch: {}

concurrency:
  group: addon-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    strategy:
      matrix:
        # matrix arch -> docker platform and HA base image arch
        include:
          - arch: amd64
            platform: linux/amd64
            base_arch: amd64
          - arch: aarch64
            platform: linux/arm64
            base_arch: aarch64
          - arch: armv7
            platform: linux/arm/v7
            base_arch: armv7
    env:
      IMAGE_NAME: ghcr.io/starlit-rocketship/amber2sigen-addon
      VERSION: 1.0.0

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build ${{ matrix.arch }} and push
        uses: docker/build-push-action@v6
        with:
          context: ./amber2sigen
          file: ./amber2sigen/Dockerfile
          platforms: ${{ matrix.platform }}
          push: true
          build-args: |
            BUILD_FROM=ghcr.io/home-assistant/${{ matrix.base_arch }}-base:2025.05.0
          tags: |
            ${{ env.IMAGE_NAME }}-${{ matrix.arch }}:latest
            ${{ env.IMAGE_NAME }}-${{ matrix.arch }}:${{ env.VERSION }}

  manifest:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      packages: write
    env:
      IMAGE_NAME: ghcr.io/starlit-rocketship/amber2sigen-addon
      VERSION: 1.0.0
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push multi-arch manifest (latest)
        run: |
          docker manifest create ${IMAGE_NAME}:latest \
            --amend ${IMAGE_NAME}-amd64:latest \
            --amend ${IMAGE_NAME}-aarch64:latest \
            --amend ${IMAGE_NAME}-armv7:latest
          docker manifest push ${IMAGE_NAME}:latest

      - name: Create and push multi-arch manifest (version)
        run: |
          docker manifest create ${IMAGE_NAME}:${VERSION} \
            --amend ${IMAGE_NAME}-amd64:${VERSION} \
            --amend ${IMAGE_NAME}-aarch64:${VERSION} \
            --amend ${IMAGE_NAME}-armv7:${VERSION}
          docker manifest push ${IMAGE_NAME}:${VERSION}
